// This file is auto-generated by `cargo run --bin generate-bindings`
// Manual edits will be overwritten.
//
// The types below are generated from Rust structs via specta.
// They match the Tauri command signatures exactly.

export interface Patient {
  id: string;
  name: string;
  age: number;
  gender: string;
  phone: string;
  email: string | null;
  address: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreatePatient {
  name: string;
  age: number;
  gender: string;
  phone: string;
  email: string | null;
  address: string | null;
}

export interface Appointment {
  id: string;
  patient_id: string;
  staff_id: string;
  title: string;
  description: string | null;
  scheduled_at: string;
  duration_minutes: number;
  status: string;
  created_at: string;
  updated_at: string;
}

export interface CreateAppointment {
  patient_id: string;
  staff_id: string;
  title: string;
  description: string | null;
  scheduled_at: string;
  duration_minutes: number;
}

export interface Staff {
  id: string;
  name: string;
  role: string;
  department: string;
  phone: string;
  email: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateStaff {
  name: string;
  role: string;
  department: string;
  phone: string;
  email: string | null;
}

export interface InventoryItem {
  id: string;
  name: string;
  category: string;
  quantity: number;
  unit: string;
  min_quantity: number;
  created_at: string;
  updated_at: string;
}

export interface CreateInventoryItem {
  name: string;
  category: string;
  quantity: number;
  unit: string;
  min_quantity: number;
}
